<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="MAIN" Id="{1845b391-745b-40f8-973d-4ad23fa36772}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	x: LREAL;
	y: LREAL;
	z: LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>